# Generated by Django 3.2.10 on 2021-12-18 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_delivery_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='apartment',
            field=models.CharField(blank=True, max_length=500, verbose_name='apartment'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='building',
            field=models.CharField(blank=True, max_length=500, verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='floor',
            field=models.CharField(blank=True, max_length=500, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='street',
            field=models.CharField(blank=True, max_length=500, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.CharField(blank=True, max_length=500, verbose_name='payment'),
        ),
    ]
