# Generated by Django 3.2.10 on 2021-12-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_basket_basketitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
