# Generated by Django 3.2.10 on 2021-12-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_basketitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='market.basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='market.item'),
        ),
    ]
